apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  namespace: homelab
  labels:
    app: pgadmin
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 2Gi
