apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-data
  namespace: homelab
  labels:
    app: memos
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
