apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  namespace: homelab
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
